;-----------------------------------------------------------------------------
; zpvars.inc
;
; Stefan Wessels, 2019
; This is free and unencumbered software released into the public domain.

;-----------------------------------------------------------------------------
.segment "ZEROPAGE"

;-----------------------------------------------------------------------------
; zero page variables
zMusicPtr:              .res 2
